server:
  port: 8085

spring:
  application:
    name:  CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/mdsaji940/HRS-microservice-config
          clone-on-start: true
